// THIS CODE WAS AUTO-GENERATED BY 'IdStructGenerator' TO COMPLETE PARTIAL STRUCT 'CharacterId'
// DO *NOT* MODIFY MANUALLY!!

using System;

namespace AO.Core.Ids
{
	public readonly partial struct CharacterId : IEquatable<CharacterId>, IFormattable
    {
        public static readonly CharacterId Empty = new(0);

        private readonly UInt32 id;

        private CharacterId(UInt32 id)
        {
            this.id = id;
        }

        public static CharacterId FromBytes(byte[] bytes, int startIndex)
        {
            return BitConverter.ToUInt32(bytes, startIndex);
        }

        public static implicit operator CharacterId(UInt32 id)
        {
            return new CharacterId(id);
        }

        public static bool operator ==(CharacterId lhs, CharacterId rhs)
        {
            return lhs.id == rhs.id;
        }

        public static bool operator !=(CharacterId lhs, CharacterId rhs)
        {
            return !(lhs == rhs);
        }

        public override bool Equals(object obj)
        {
            return obj is CharacterId other && other.id == id;
        }

        public static int Size()
        {
            return sizeof(UInt32);
        }

        public bool Equals(CharacterId other)
        {
            return other.id == id;
        }

        public override int GetHashCode()
        {
            return id.GetHashCode();
        }

        public override string ToString()
        {
            return id.ToString();
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return id.ToString(format, formatProvider);
        }

        public UInt32 AsPrimitiveType()
        {
            return id;
        }

        public static CharacterId Parse(string value)
        {
            return UInt32.Parse(value);
        }

        public static bool TryParse(string value, out CharacterId result)
        {
            bool parsed = UInt32.TryParse(value, out var outVal);
            result = outVal;
            return parsed;
        }
	}
}