// THIS CODE WAS AUTO-GENERATED BY 'IdStructGenerator' TO COMPLETE PARTIAL STRUCT 'ItemId'
// DO *NOT* MODIFY MANUALLY!!

using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using Newtonsoft.Json;

namespace AO.Core.Ids
{
	[JsonConverter(typeof(ItemIdJsonConverter))]
	public readonly partial struct ItemId : IEquatable<ItemId>, IFormattable
    {
        public static readonly ItemId Empty = new(0);

        private readonly UInt16 id;

        private ItemId(UInt16 id)
        {
            this.id = id;
        }

        public static ItemId FromBytes(byte[] bytes, int startIndex)
        {
            return BitConverter.ToUInt16(bytes, startIndex);
        }

        public static implicit operator ItemId(UInt16 id)
        {
            return new ItemId(id);
        }

        public static bool operator ==(ItemId lhs, ItemId rhs)
        {
            return lhs.id == rhs.id;
        }

        public static bool operator !=(ItemId lhs, ItemId rhs)
        {
            return !(lhs == rhs);
        }

        public override bool Equals(object obj)
        {
            return obj is ItemId other && other.id == id;
        }

        public static int Size()
        {
            return sizeof(UInt16);
        }

        public bool Equals(ItemId other)
        {
            return other.id == id;
        }

        public override int GetHashCode()
        {
            return id.GetHashCode();
        }

        public override string ToString()
        {
            return id.ToString();
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return id.ToString(format, formatProvider);
        }

        public UInt16 AsPrimitiveType()
        {
            return id;
        }

        public static ItemId Parse(string value)
        {
            return UInt16.Parse(value);
        }

        public static bool TryParse(string value, out ItemId result)
        {
            bool parsed = UInt16.TryParse(value, out var outVal);
            result = outVal;
            return parsed;
        }
        
		public static Dictionary<ItemId, TValue> ParseDictionary<TValue>([NotNull] IDictionary<string, TValue> baseDictionary)
        {
            var dict = new Dictionary<ItemId, TValue>(baseDictionary.Count);
            foreach (var (key, value) in baseDictionary)
                dict.Add(UInt16.Parse(key), value);
            return dict;
        }

        public class ItemIdJsonConverter : JsonConverter<ItemId>
        {
            public override void WriteJson(JsonWriter writer, ItemId value, JsonSerializer serializer)
            {
                writer.WriteValue(value.AsPrimitiveType());
            }

            public override ItemId ReadJson(JsonReader reader, Type objectType, ItemId existingValue, bool hasExistingValue, JsonSerializer serializer)
            {
                return new ItemId(serializer.Deserialize<UInt16>(reader));
            }
        }
    }
}