// THIS CODE WAS AUTO-GENERATED BY 'IdStructGenerator' TO COMPLETE PARTIAL STRUCT 'QuestId'
// DO *NOT* MODIFY MANUALLY!!

using System;
using System.Collections.Generic;
using JetBrains.Annotations;
using Newtonsoft.Json;

namespace AO.Core.Ids
{
	[JsonConverter(typeof(QuestIdJsonConverter))]
	public readonly partial struct QuestId : IEquatable<QuestId>, IFormattable
    {
        public static readonly QuestId Empty = new(0);

        private readonly UInt16 id;

        private QuestId(UInt16 id)
        {
            this.id = id;
        }

        public static QuestId FromBytes(byte[] bytes, int startIndex)
        {
            return BitConverter.ToUInt16(bytes, startIndex);
        }

        public static implicit operator QuestId(UInt16 id)
        {
            return new QuestId(id);
        }

        public static bool operator ==(QuestId lhs, QuestId rhs)
        {
            return lhs.id == rhs.id;
        }

        public static bool operator !=(QuestId lhs, QuestId rhs)
        {
            return !(lhs == rhs);
        }

        public override bool Equals(object obj)
        {
            return obj is QuestId other && other.id == id;
        }

        public static int Size()
        {
            return sizeof(UInt16);
        }

        public bool Equals(QuestId other)
        {
            return other.id == id;
        }

        public override int GetHashCode()
        {
            return id.GetHashCode();
        }

        public override string ToString()
        {
            return id.ToString();
        }

        public string ToString(string format, IFormatProvider formatProvider)
        {
            return id.ToString(format, formatProvider);
        }

        public UInt16 AsPrimitiveType()
        {
            return id;
        }

        public static QuestId Parse(string value)
        {
            return UInt16.Parse(value);
        }

        public static bool TryParse(string value, out QuestId result)
        {
            bool parsed = UInt16.TryParse(value, out var outVal);
            result = outVal;
            return parsed;
        }
        
		public static Dictionary<QuestId, TValue> ParseDictionary<TValue>([NotNull] IDictionary<string, TValue> baseDictionary)
        {
            var dict = new Dictionary<QuestId, TValue>(baseDictionary.Count);
            foreach (var (key, value) in baseDictionary)
                dict.Add(UInt16.Parse(key), value);
            return dict;
        }

        public class QuestIdJsonConverter : JsonConverter<QuestId>
        {
            public override void WriteJson(JsonWriter writer, QuestId value, JsonSerializer serializer)
            {
                writer.WriteValue(value.AsPrimitiveType());
            }

            public override QuestId ReadJson(JsonReader reader, Type objectType, QuestId existingValue, bool hasExistingValue, JsonSerializer serializer)
            {
                return new QuestId(serializer.Deserialize<UInt16>(reader));
            }
        }
    }
}